import { readFileSync, writeFileSync } from 'node:fs';
import { makeMotor, move } from '../shared/physics.js';
import { neutralInput, type Input, type Role, type Vec3 } from '../shared/types.js';
const definitions: { name: string; start: Vec3; role: Role; segments: { ticks: number; input: Partial<Input> }[] }[] = [
  { name: 'hider-run-sprint-stop', start: { x: 20, y: 0, z: 20 }, role: 'hider', segments: [{ ticks: 60, input: { mz: 1 } }, { ticks: 90, input: { mz: 1, sprint: true } }, { ticks: 60, input: {} }] },
  { name: 'seeker-diagonal-turn', start: { x: -20, y: 0, z: 20 }, role: 'seeker', segments: [{ ticks: 90, input: { mx: 1, mz: 1 } }, { ticks: 60, input: { mz: 1, yaw: 1.2, pitch: 0.3 } }] },
  { name: 'jump-hold-land', start: { x: 20, y: 0, z: 20 }, role: 'hider', segments: [{ ticks: 20, input: { jump: true, mz: 1 } }, { ticks: 90, input: { jump: true } }, { ticks: 10, input: {} }, { ticks: 20, input: { jump: true } }] },
  { name: 'dash-wall-slide', start: { x: 12, y: 0, z: 4 }, role: 'hider', segments: [{ ticks: 20, input: { mz: 1, dash: true } }, { ticks: 120, input: { mz: 1, mx: 0.4 } }] },
  { name: 'stairs-balcony', start: { x: 11, y: 0, z: -5 }, role: 'hider', segments: [{ ticks: 90, input: { mz: 1 } }, { ticks: 60, input: { mz: 1 } }, { ticks: 60, input: { mx: 1 } }] },
  { name: 'no-seeker-dash', start: { x: 20, y: 0, z: 20 }, role: 'seeker', segments: [{ ticks: 60, input: { dash: true, mz: 1 } }] },
];
const cases = definitions.map(definition => {
  const motor = makeMotor(definition.start);
  const segments = definition.segments.map(segment => {
    const input = { ...neutralInput(), ...segment.input };
    for (let tick = 0; tick < segment.ticks; tick++) move(motor, input, definition.role);
    return { ticks: segment.ticks, input, expected: { ...motor } };
  });
  return { ...definition, segments };
});
const text = JSON.stringify({ description: 'Generated by scripts/movement-fixtures.ts from the browser motor. Do not hand-edit expected states.', cases }) + '\n';
const path = 'tests/fixtures/movement.json';
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== text) throw new Error('Movement fixtures changed. Review the physics change, run npm run fixtures, then verify cargo test.');
  console.log('Browser movement fixtures match.');
} else { writeFileSync(path, text); console.log(`Wrote ${cases.length} movement scenarios to ${path}.`); }
